### ISSUE TITLE
Error when Manabox csv contains Binder columns

### ISSUE THREAD

**Issue by mattbodensteiner** [dyashman/mb2cs#1]
Some exports from Manabox evidently contain columns for 'Binder Name' and 'Binder Type' which throws off the indexing of the columns when reading the csv data.

![image](https://github.com/dyashman/mb2cs/assets/67394400/23f1e8be-20ff-4052-8286-15f6386524db)

Removing these columns before running the csv through the converter is a simple workaround but might be something to consider having built-in ability to handle if users aren't able to identify the problem.

Cheers,
~ Bodey (Cardsphere)

**Comment by dyashman** [comment]
Fixed - Updated script to read the headers and return their offsets instead of assuming they would always be in the exact same order/position mine were.
