### ISSUE TITLE
Various cards & editions not converted properly

### ISSUE THREAD

**Issue by mattbodensteiner** [dyashman/mb2cs#2]
Had a user send me their Manabox csv to convert to CS. They had 55 entries that did not import to CS correctly but several common sets among them. I've paired it down to just those entries.
[Manabox_Not_Imported_08-30-2024.csv](https://github.com/user-attachments/files/16823205/Manabox_Not_Imported_08-30-2024.csv)

Thought it might be useful to provide more data for the whack-a-mole effort.

Cheers,
~ Bodey

**Comment by dyashman** [comment]
Should all be fixed except Incinerate - the version in the csv looks like a digital-only version and I can't find that specific version in the app. CardSphere also has no foil version of that card, so it fails to upload even if I convert it to the Player Rewards version.
